from enum import Enum

class CMD(Enum):
    GET_PITCH_ROLL = 0
    GET_FROM_GYROSCOPE = 1
    STORE_IMU_DATA = 2
    SEND_IMU_DATA = 3
    TOF_DATA = 4
    STORE_DUAL_TOF_IMU_DATA = 5
    SEND_DUAL_TOF_IMU_DATA = 6
    SET_PID_GAINS = 7
    START_PID_CONTROL = 8
    GET_PID_DATA = 9
    SET_ORIENTATION_GAINS = 10
    START_ORIENTATION_CONTROL = 11
    GET_ORIENTATION_DATA = 12
    START_STEP_RESPONSE = 13
    SEND_STEP_DATA = 14
    SET_KF_PARAMETERS = 15
    GET_STUNT_DATA = 16